# Generated by Django 2.1.4 on 2019-04-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='completed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
